SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 800

BOARD_WIDTH = 500
BOARD_HEIGHT = 800

CARD_WIDTH = 100
CARD_HEIGHT = 100

SCREEN_TITLE = "Blockade"
# If true, default width and height will be ignored and overridden
SCREEN_FULLSCREEN = False
PLAYER_SCREEN = "P2"

FRAMERATE = 5